// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: embedding_service.proto

package embedding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gender        string                 `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Occupation    int32                  `protobuf:"varint,4,opt,name=occupation,proto3" json:"occupation,omitempty"`
	Zipcode       string                 `protobuf:"bytes,5,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_embedding_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_embedding_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserRequest) GetOccupation() int32 {
	if x != nil {
		return x.Occupation
	}
	return 0
}

func (x *UserRequest) GetZipcode() string {
	if x != nil {
		return x.Zipcode
	}
	return ""
}

type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_embedding_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_embedding_service_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_embedding_service_proto protoreflect.FileDescriptor

const file_embedding_service_proto_rawDesc = "" +
	"\n" +
	"\x17embedding_service.proto\x12\tembedding\"\x8a\x01\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\tR\x06gender\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1e\n" +
	"\n" +
	"occupation\x18\x04 \x01(\x05R\n" +
	"occupation\x12\x18\n" +
	"\azipcode\x18\x05 \x01(\tR\azipcode\"1\n" +
	"\x11EmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding2c\n" +
	"\x10EmbeddingService\x12O\n" +
	"\x15GenerateUserEmbedding\x12\x16.embedding.UserRequest\x1a\x1c.embedding.EmbeddingResponse\"\x00B(Z&recommendation-service/proto/embeddingb\x06proto3"

var (
	file_embedding_service_proto_rawDescOnce sync.Once
	file_embedding_service_proto_rawDescData []byte
)

func file_embedding_service_proto_rawDescGZIP() []byte {
	file_embedding_service_proto_rawDescOnce.Do(func() {
		file_embedding_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embedding_service_proto_rawDesc), len(file_embedding_service_proto_rawDesc)))
	})
	return file_embedding_service_proto_rawDescData
}

var file_embedding_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_embedding_service_proto_goTypes = []any{
	(*UserRequest)(nil),       // 0: embedding.UserRequest
	(*EmbeddingResponse)(nil), // 1: embedding.EmbeddingResponse
}
var file_embedding_service_proto_depIdxs = []int32{
	0, // 0: embedding.EmbeddingService.GenerateUserEmbedding:input_type -> embedding.UserRequest
	1, // 1: embedding.EmbeddingService.GenerateUserEmbedding:output_type -> embedding.EmbeddingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_embedding_service_proto_init() }
func file_embedding_service_proto_init() {
	if File_embedding_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embedding_service_proto_rawDesc), len(file_embedding_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embedding_service_proto_goTypes,
		DependencyIndexes: file_embedding_service_proto_depIdxs,
		MessageInfos:      file_embedding_service_proto_msgTypes,
	}.Build()
	File_embedding_service_proto = out.File
	file_embedding_service_proto_goTypes = nil
	file_embedding_service_proto_depIdxs = nil
}
